FROM python:3.9-slim

WORKDIR /infection

COPY stockholm /infection
COPY extensions /infection

RUN pip install --upgrade pip && \
	pip install cryptography \
	argparse \
	tqdm

CMD [ "tail", "-f", "/dev/null" ]