# Attacker dockerfile
FROM ubuntu

RUN apt update && apt install -y python3 python3-pip iputils-ping net-tools tcpdump python3.12-venv

RUN python3 -m venv /root/attacker/my-venv

RUN /root/attacker/my-venv/bin/pip install scapy ipaddress argparse

WORKDIR /root/attacker

COPY ./inquisitor /root/attacker/

# ENTRYPOINT [ "/root/attacker/my-venv/bin/python3", "/root/attacker/inquisitor" ]
CMD [ "tail", "-f", "/dev/null" ]